micronaut:
  application:
    name: rest

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

  server:
    port: ${PORT:8081}
    cors:
      enabled: true
    context-path: ${CONTEXT_PATH:/}

  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
    intercept-url-map:
      - pattern: /swagger/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        http-method: GET
        access:
          - isAnonymous()

  openapi:
    views:
      spec: |
        swagger-ui.enabled=true,
        swagger-ui.theme=flattop
    swagger-ui:
      enabled: true



jackson:
  serialization-inclusion: NON_ABSENT # Omit null and Optional.empty(), but include empty collections
  serialization:
    indent-output: true # Pretty-print JSON
netty:
  default:
    allocator:
      max-order: 3
